import type { Metadata } from "next";
import { Montserrat, Lora, Poppins, Noto_Sans_JP, Noto_Serif_JP } from '@next/font/google'
import Header from './components/Header';
import Footer from './components/Footer';
import "@/app/styles/globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-montserrat',
});

const lora = Lora({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-lora',
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-poppins',
});

const notoSansJP = Noto_Sans_JP({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-noto-sans-jp',
});

const notoSerifJP = Noto_Serif_JP({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-noto-serif-jp',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${montserrat.variable} ${lora.variable} ${poppins.variable} ${notoSansJP.variable} ${notoSerifJP.variable}`}>
        <Header />
          <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
